//import styles from '../styles/portfolio.module.css';
import Head from 'next/head';
import Earth from '../components/earth.jsx';
import Box from '../components/box.jsx';
import { motion, useInView } from "framer-motion"
import { useEffect, useRef, useState } from 'react';
import React from "react";
import UseAnimations from "react-useanimations";
import menu3 from 'react-useanimations/lib/menu3';






function Section(props) {
  const ref = useRef(null);
  const isInView = useInView(ref, {margin: "1px 0px -10px 0px", once: false,amount: 'some' });
  let  updatedprops = props;
  try{
  updatedprops = updatedprops.children.props? {...updatedprops.children.props, style :{}} : updatedprops;
  }catch(e){}
  try{
  updatedprops =  {...updatedprops.children.props.style, transform : isInView ? "Scale(1)" : "Scale(0) ", opacity: isInView ? 1 : 0, transition: "all 0.4s ease-in-out 0.1s"}
  }catch(e){}
  console.log(updatedprops.children)




  return (
    <props.element ref={ref}  className={props.className}>
      <span className={props.spanClassName}

      >
      {updatedprops.children}
      </span>
    </props.element >
  );
}

function Svg({mobileNav}){
  return(
    <svg className='' xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
    <g style={{transform :mobileNav?'translate(-5px, 12px)  rotate(-45deg)':''}} className="transition-all duration-300 ease-linear  " id="Group_1" data-name="Group 1" transform="translate(4 4)">
      <path id="Path_1" data-name="Path 1" d="M3,18H21" fill="none" stroke="#ebebeb" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
    </g>
    <g style={{opacity: mobileNav? 0 : 1 }} className="transition-all duration-300 ease-linear" id="Group_2" data-name="Group 2" transform="translate(4 4)">
      <path id="Path_2" data-name="Path 2" d="M3,12H21" fill="none" stroke="#ebebeb" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
    </g>
    <g style={{transform : mobileNav?'translate(12px, 3.5px)  rotate(45deg)': ''}} className="transition-all duration-300 ease-linear " id="Group_3" data-name="Group 3" transform="translate(4 4)">
      <path id="Path_3" data-name="Path 3" d="M3,6H21" fill="none" stroke="#ebebeb" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
    </g>
    <rect id="Rectangle_1" data-name="Rectangle 1" width="32" height="32" fill="none" />
  </svg>
  )
}

export default function Portfolio() {
  // nav----------------------------------
  const [mobileNav , setMobileNav] = useState(false);
  const [isNav , setIsNav] = useState(true);           // it is to hide nav after animation is complete 
  const navstate = () => { setMobileNav(!mobileNav) };
  useEffect(() => {!mobileNav? setTimeout(()=>{setIsNav(false);console.log('ddd')}, 300):setIsNav(true) }, [mobileNav]);   // it is to hide nav after animation is complete



  return (
    <>
      <Head>
        <title>Asadullah Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  className="text-white font-poppins">
        <section  className="h-12 md:h-20 w-full z-10  border-white absolute flex justify-between h-full flex-wrap md:flex-nowrap">
          <Section  element='div' className='h-full aspect-square p-2'>
            <img style={{display : 'none'}} className="h-full w-full object-cover" src="/portfolio/herobackground/profile.svg" />
          </Section>
          <button className={`aspect-square w-max border-yellow-400 font-black h-full aspect-square`} onClick={navstate}>
            <Svg mobileNav = {mobileNav} />
          </button>
          <div className={`h-fit absolute top-10 right-0 opacity-90 m-3 p-3 bg-[#424242] rounded font-bold  text-right border-[1px] border-white transition-all duration-300 ease-linear ${mobileNav ? 'opacity-100' : 'opacity-0'} ${isNav? '' : 'hidden'}` }>
            <ul className="flex flex-col md:flex-row ">
              <a><li className="pt-2">HOME</li></a>
              <a><li className="pt-2">SEVICES</li></a>
              <a><li className="pt-2">Portfolio</li></a>
              <a><li className="pt-2">ABOUT</li></a>
              <a><li className="pt-2">CONTACT</li></a>
            </ul>
          </div>
        </section>
        <Section element='section' className="bg-[url('/portfolio/herobackground/tint.svg'),url('/portfolio/herobackground/vec6.jpg')] h-screen bg-cover bg-no-repeat bg-center pt-12 md:pt-20" spanClassName="md:flex flex-row h-full ">
          <div className=" m-2 p-9 basis-1/2 md:mt-[auto] md:mb-[auto]" >
            <h1 className=" text-7xl leading-none tracking-wide font-black ">MUHAMMAD ASADULLAH</h1> <h1 className="mt-2 text-[#aca6ff] text-7xl leading-none tracking-wide font-black">Full Stack Web Developer.</h1>
            <div className="text-center mt-[20%]" ><button className=" bg-[#030284] aspect-[6/2] p-3 rounded-full m-5 border-2 w-max border-yellow-400 font-bold">DOWNLOAD CV</button></div>
          </div>
          <div className="bg-[url('/portfolio/herobackground/profile.svg')] bg-contain bg-no-repeat bg-center aspect-[10/9] md:h-full md:aspect-auto md:basis-1/2   m-2 " />
          <div className="text-center md:hidden" ><button className=" bg-[#030284] aspect-[6/2] p-3 rounded-full m-5 border-2 w-max border-yellow-400 font-bold">DOWNLOAD CV</button></div>
        </Section>
        <Section element='section' className="h-screen">
            <h1 className=' text-9xl inline-block'  >Hello world</h1>
        </Section>
        <Section element='section'>
          <p className="">
            Hello my name is Asadullah
          </p>
        </Section>
      </div>
    </>
  );
}